language: python
python:
- 3.7
install:
- pip install -r requirements.txt
script:
- pytest tests.py
deploy:
  provider: heroku
  api_key:
    secure: k1Q5xtUIed9GsL/tBwWrWfb734rsj7wt1pd97Q42DNbtFa0pkX0eGNahdImClvxBgCsLP79uJ97IdgXghHvo+EIjtzXqnR4J1M/ZusSMSvFY9g0iL6RFxTrxE8c36Xbnaa9wh3lLk4jncaqXbhL5g8oOba64MFlt/sE/ZhJ+3YDDTJOc+Ej3HhT7zQU9oJlo153Q5kJ+i6XaKUx4dKcHZtpFYXA5rvzmLtldcXz4UdteDqUkvP+iDfdD7asOufS40uqgCjQUyRDcCN2KZgBpkKiAXnLJTiRWQKFC//P25Y3baOWoSK6DlVhViL1g6B2S/1LF7KOORBwSTYdeWSa7gpvA0XRyMzkekzKp0wztXDGhUEugsBenSnRBtOAJhLnsDtzLvPoWGC5d2oeH7TZU53UyDUEA7yR7Zx9mkjwkaco6q1PmPQbiFpDEWA9j5+EieixMX4aMLeTmvZFs/aE23UeA9qkHfA3FKaHyW2MaYrILoRr3nFdnWuBlAo8CdSzbEfO53gCg4xVStXYczqdRo0hNp0uFYl3T+4kBWyRxuSH5U3mrEILTAddB2tsvuKGNc03vYI/FcKy5bZQeyjv67oYZ0di7Od4vBCOdjmXoAv6WAjEHpHW4PFu62QdJXbhsCGDcagPXVn6YutQrPqAi3aRhaX6TwMqt0xhcbRr30/Q=
  app: twitter-bot-42491
